### ISSUE TITLE
Files not being deleted?

### ISSUE THREAD

**Issue by matthewfiedler** [drewminns/slack#1] opened 2016-04-22 19:51 UTC
We've "exceeded our storage limit" on slack and i've been trying to delete via the deletron bot but the files don't appear to actually be deleted? if i delete a bunch and then click "get files" once more, they all show up again. Am I missing something?

**Comment by drewminns** [comment] 2016-04-25 20:03
Hmmmm. I'll take a peek. This may be an issue with the Slack API, but I'll add additional checking for success.

**Comment by drewminns** [comment] 2016-04-26 01:49
The issue is permissions for the authenticated user. I'm going to add better checking for the level of user.

**Comment by malinin13** [comment] 2016-04-26 16:28
Having the same issue, that's because I'm not an admin of the channel. Checking permissions will fix that, yeah.

**Comment by drewminns** [comment] 2016-04-27 00:05
Hoping you can take a peek now and let me know. Made some changes to the logic to what kind of data is returned based on your user role. As well, I added some checking on the DESTROY_FILE reducer to handle a successful deletion.

You can take a peek here - https://github.com/drewminns/slack/commit/85f2c2d3ed1167a106da525453458c1dfc8525a9

If you can confirm on your end that it works, I'll close the issue.
Thanks!

**Comment by matthewfiedler** [comment] 2016-04-28 00:25
Makes sense -- i'm logged in now, trying to delete but I click delete and nothing happens. Assume that might have to do with me not being an admin... is that right?

**Comment by drewminns** [comment] 2016-04-28 01:07
I made some further changes right now that wait for the resolve of the promise before changing state. I hope everything is solved now. 

There was some weird unexpected behaviour. Programming amirite?! ¯_(ツ)_/¯

**Comment by drewminns** [comment] 2016-05-03 14:05
Closing this assuming that it's ok now.

**Closed as completed by drewminns** 2016-05-03 14:05 UTC
